---
# Tasks related to user management

- name: Ensure the user is present
  user:
    name: "{{ user_name }}"
    state: present
    create_home: yes

- name: Set a password for the user
  user:
    name: "{{ user_name }}"
    password: "{{ 'password' | password_hash('sha512') }}"
  no_log: true

- name: Add the user to the sudoers group
  user:
    name: "{{ user_name }}"
    groups: sudo
    append: yes
